### PR TITLE
Add ability to customize whether the bot is deafened on join or not.

### PR DESCRIPTION
**Pull request by strangenesX**

### CODE REVIEW

**Comment by Devoxin** [comment]
Purpose? I don't believe selfDeaf changes anything regarding whether the bot can receive voice from users or not.

**Comment by NovusTheory** [comment]
It seems like a wasteful API property and really serves no purpose besides being visual. I really don't see a reason to implement this. Receive data is discarded anyways. Is a tiny icon really that important?

**Comment by ZanePereira** [comment]
As @strangenesX said, its purely cosmetic but still, i would like to see this property be added. I really have no idea at all why people are opposing this, its just a neat customization feature.

**Comment by Devoxin** [comment]
Self-Deafening most definitely does not affect whether **bots** can receive voice data from speaking users @NovusTheory

**Pull request merged**
